# Generated by Django 5.1.6 on 2025-05-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
    ]
